variables:
  # PROD Environment
  ENVIRONMENT: ADB-IAC-PROD
  RESOURCE_GROUP: pmw2diharcag01
  LOCATION: westus2
  SERVICECONNECTION_RG: PRD-CORPTB-CICD-SPK0038145
  SUBSCRIPTIONID: "531b7d12-fb78-497c-bd32-d1eda892743b"